[package]
name = "archetype"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
euclid = "*"
gtk = "0.9.0"
gio = "0.9.0"
num-traits = "0.2.12"
smallvec = "1.4.1"
